on:
  push:
    branches:
      - main
jobs:
  DEV:
    runs-on: ubuntu-latest
    environment: Development
    steps:
      - name: Checkout code from main branch
        uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v3
      
      - name: Setup sam-cli
        uses: aws-actions/setup-sam@v2
      
      - name : Setup aws-cli 
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: {{cookiecutter.AWS_region}}

      - name: Build sam-application # sam build
        if: github.ref == 'refs/head/main'
        run: sam build {{cookiecutter.function_name}} --use-container -t template-dev.yaml
      
      - name: Deploy sam-application to region {{cookiecutter.AWS_region}} # sam deploy
        run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name {{cookiecutter.function_name}} --s3-bucket {{cookiecutter.S3_code_store_name_DEV}} CAPABILITY_IAM --region {{cookiecutter.IAM_region}}

  PROD:
    needs: DEV
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Checkout code from main branch
        uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v3
      
      - name: Setup sam-cli
        uses: aws-actions/setup-sam@v2
      
      - name : Setup aws-cli 
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: {{cookiecutter.AWS_region}}

      - name: Build sam-application # sam build
        if: github.ref == 'refs/head/main'
        run: sam build {{cookiecutter.function_name}} --use-container -t template-prod.yaml
      
      - name: Deploy sam-application to region {{cookiecutter.AWS_region}} # sam deploy
        run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name {{cookiecutter.function_name}} --s3-bucket {{cookiecutter.S3_code_store_name_PROD}} CAPABILITY_IAM --region {{cookiecutter.IAM_region}}